# -*- coding: utf-8 -*-
"""code_augmentation+train_model+evaluate_model+test_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PO3G5Jei7LAdhISJnGKl8XXnnacLBiFx

การ AUGMENTATION
"""

import cv2
import numpy as np
import random
import albumentations as A
from pathlib import Path
from collections import Counter
from tqdm import tqdm

# =========================================================
# 1. ตั้งค่าพื้นฐาน
# =========================================================
# เปลี่ยนเป็น Path ของคุณใน Google Drive
PROJECT_PATH = "/content/drive/MyDrive/phase4/3"

DATASET_ROOT = f"{PROJECT_PATH}/train"
OUTPUT_ROOT = f"{PROJECT_PATH}/train_aug_obb"

IMAGE_DIR = Path(DATASET_ROOT) / "images"
LABEL_DIR = Path(DATASET_ROOT) / "labels"

OUT_IMAGE_DIR = Path(OUTPUT_ROOT) / "images"
OUT_LABEL_DIR = Path(OUTPUT_ROOT) / "labels"
PREVIEW_DIR = Path(OUTPUT_ROOT) / "preview"

# ตั้งค่าการขยายข้อมูล
OUTPUT_SIZE = (640, 640)      # ปรับขนาดภาพปลายทาง
BASE_AUG_PER_IMAGE = 2        # เพิ่มขั้นต่ำกี่เท่าสำหรับภาพปกติ
MAX_EXTRA_AUG_FOR_RARE = 4    # เพิ่มพิเศษให้คลาสที่หาดูยาก
RARE_CLASS_THRESHOLD_RATIO = 0.50
COPY_ORIGINALS = True         # คัดลอกรูปต้นฉบับไปด้วยหรือไม่
SAVE_PREVIEW = True           # สร้างภาพตัวอย่างที่วาดกล่อง OBB หรือไม่

CLASS_NAMES = {
  0: "Crack",
  1: "Efflorescence",
  2: "Porous_Defect",
  3: "Rust_Stained_Exposure",
  4: "Spalling",
  5: "Steel_Exposure",
  6: "strain"
}

# =========================================================
# 2. UTILS & FUNCTIONS (ส่วนการทำงานหลังบ้านสำหรับ OBB)
# =========================================================
def ensure_dir(path: Path):
    path.mkdir(parents=True, exist_ok=True)

def load_yolo_obb_labels(label_path: Path):
    """ อ่านไฟล์ Label แบบ OBB (มี 9 ค่า: class_id, x1, y1, x2, y2, x3, y3, x4, y4) """
    polygons_norm, class_labels = [], []
    if not label_path.exists(): return polygons_norm, class_labels
    with open(label_path, "r", encoding="utf-8") as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) == 9:
                cls_id = int(float(parts[0]))
                pts = [float(x) for x in parts[1:]]
                # เก็บเป็นคู่พิกัด Normalized (0-1)
                poly = [(pts[0], pts[1]), (pts[2], pts[3]), (pts[4], pts[5]), (pts[6], pts[7])]
                polygons_norm.append(poly)
                class_labels.append(cls_id)
    return polygons_norm, class_labels

def save_yolo_obb_labels(label_path: Path, polygons_abs, class_labels, img_w, img_h):
    """ แปลงพิกัด Pixel จริง กลับเป็น Normalized (0-1) แล้วเซฟไฟล์ """
    with open(label_path, "w", encoding="utf-8") as f:
        for cls_id, poly in zip(class_labels, polygons_abs):
            norm_pts = []
            for x, y in poly:
                # แปลงและป้องกันค่าล้นขอบ (Clipping)
                nx = min(max(x / img_w, 0.0), 1.0)
                ny = min(max(y / img_h, 0.0), 1.0)
                norm_pts.extend([nx, ny])

            line = f"{cls_id} " + " ".join([f"{v:.6f}" for v in norm_pts]) + "\n"
            f.write(line)

def draw_bboxes_obb(image_bgr, polygons_abs, class_labels):
    """ วาดกล่องเอียงลงบนภาพ Preview """
    out = image_bgr.copy()
    for poly, cls_id in zip(polygons_abs, class_labels):
        # แปลงเป็น array สำหรับวาดรูป polygon
        pts = np.array(poly, np.int32).reshape((-1, 1, 2))
        color = (int((37*cls_id)%255), int((17*cls_id+80)%255), int((29*cls_id+160)%255))
        cv2.polylines(out, [pts], isClosed=True, color=color, thickness=2)
        cv2.putText(out, f"{CLASS_NAMES.get(cls_id, cls_id)}", (pts[0][0][0], max(15, pts[0][0][1]-5)), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)
    return out

# ท่าทางการแปลงภาพ
# **สำคัญ:** เปลี่ยนมาใช้ keypoint_params เพื่อดึงจุด 4 มุมของ OBB ไปหมุนแทน
TRANSFORM = A.Compose([
    A.OneOf([
        A.RandomBrightnessContrast(p=1),
        A.CLAHE(p=1),
        A.HueSaturationValue(p=1),
    ], p=0.7),
    A.HorizontalFlip(p=0.5),
    A.OneOf([
        A.Affine(rotate=(-15, 15), translate_percent=(-0.1, 0.1), p=1),
        A.Perspective(scale=(0.05, 0.1), p=1),
    ], p=0.6),
    A.GaussianBlur(blur_limit=(3, 5), p=0.3),
    A.Resize(height=OUTPUT_SIZE[0], width=OUTPUT_SIZE[1], p=1.0)
], keypoint_params=A.KeypointParams(format="xy", remove_invisible=False))
# remove_invisible=False สำคัญมาก! เพื่อกันไม่ให้จุดมุมหายไประหว่างหมุนภาพ

# =========================================================
# 3. MAIN PROCESS (เริ่มประมวลผล)
# =========================================================
def run_augmentation():
    if not IMAGE_DIR.exists() or not LABEL_DIR.exists():
        print(f"❌ ไม่พบโฟลเดอร์ภาพหรือ Label ใน: {DATASET_ROOT}")
        return

    ensure_dir(OUT_IMAGE_DIR)
    ensure_dir(OUT_LABEL_DIR)
    if SAVE_PREVIEW: ensure_dir(PREVIEW_DIR)

    img_files = sorted([p for p in IMAGE_DIR.iterdir() if p.is_file() and p.suffix.lower() in {".jpg", ".jpeg", ".png"}])
    if not img_files:
        print("❌ ไม่พบไฟล์รูปภาพในโฟลเดอร์ที่ระบุเลยครับ")
        return

    # 1. วิเคราะห์คลาส
    all_classes = []
    img_to_data = {}
    for p in img_files:
        polygons_norm, labels = load_yolo_obb_labels(LABEL_DIR / f"{p.stem}.txt")
        all_classes.extend(labels)
        img_to_data[p] = (polygons_norm, labels)

    counter = Counter(all_classes)
    max_count = max(counter.values()) if counter else 0
    rare_classes = {c for c, count in counter.items() if count <= max_count * RARE_CLASS_THRESHOLD_RATIO}

    print(f"✅ พบภาพทั้งหมด: {len(img_files)} ภาพ")
    print(f"📊 สถิติคลาสต้นฉบับ: {dict(counter)}")

    # 2. เริ่มกระบวนการทำงาน
    for p in tqdm(img_files, desc="Processing Images"):
        polygons_norm, labels = img_to_data[p]
        img = cv2.imread(str(p))
        if img is None: continue

        orig_h, orig_w = img.shape[:2]

        # แปลงพิกัด Normalized (0-1) ให้เป็น Pixel จริงสำหรับการทำ Augmentation
        polygons_abs = [[(x*orig_w, y*orig_h) for x, y in poly] for poly in polygons_norm]

        # คัดลอกไฟล์เดิมลงโฟลเดอร์ใหม่ (ปรับขนาดให้ตรงตาม OUTPUT_SIZE)
        if COPY_ORIGINALS:
            img_resized = cv2.resize(img, (OUTPUT_SIZE[1], OUTPUT_SIZE[0]))
            cv2.imwrite(str(OUT_IMAGE_DIR / p.name), img_resized)
            # เซฟ label เดิม โดยไม่ต้องคำนวณพิกัดใหม่ เพราะเราใช้ค่า Normalized เดิมได้เลย
            save_yolo_obb_labels(OUT_LABEL_DIR / f"{p.stem}.txt", polygons_norm, labels, 1.0, 1.0)

        # ==========================================
        # ขั้นตอน Augmentation (ปั๊มภาพ)
        # ==========================================
        if not polygons_abs: continue

        n_aug = BASE_AUG_PER_IMAGE
        if any(c in rare_classes for c in labels):
            n_aug += MAX_EXTRA_AUG_FOR_RARE

        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        # แตกกลุ่ม OBB เป็นจุดๆ รวมกัน (1 กล่อง = 4 จุด) เพื่อให้ไลบรารีประมวลผลได้
        flat_keypoints = [pt for poly in polygons_abs for pt in poly]

        for i in range(n_aug):
            try:
                # สั่งหมุน/พลิกรูปภาพพร้อมจุดทั้งหมด
                augmented = TRANSFORM(image=img_rgb, keypoints=flat_keypoints)
                aug_img = cv2.cvtColor(augmented["image"], cv2.COLOR_RGB2BGR)
                aug_kp = augmented["keypoints"]

                # ประกอบร่างจุด 4 จุด กลับมาเป็น 1 กล่อง OBB เหมือนเดิม
                aug_polygons = [aug_kp[j:j+4] for j in range(0, len(aug_kp), 4)]

                fname = f"{p.stem}_aug{i}"
                cv2.imwrite(str(OUT_IMAGE_DIR / f"{fname}{p.suffix}"), aug_img)

                # เซฟ Label เป็นแบบ OBB โดยอิงจากขนาดภาพใหม่ (OUTPUT_SIZE)
                save_yolo_obb_labels(OUT_LABEL_DIR / f"{fname}.txt", aug_polygons, labels, OUTPUT_SIZE[1], OUTPUT_SIZE[0])

                if SAVE_PREVIEW and random.random() < 0.1:
                    preview = draw_bboxes_obb(aug_img, aug_polygons, labels)
                    cv2.imwrite(str(PREVIEW_DIR / f"{fname}_preview.jpg"), preview)

            except Exception as e:
                print(f"\n⚠️ ข้ามภาพ {p.name} augmentation ที่ {i} เนื่องจาก Error: {e}")
                continue

    print("\n✨ ปั๊มข้อมูลแบบ OBB เสร็จเรียบร้อย!")
    print(f"📁 บันทึกข้อมูลใหม่ไว้ที่: {OUTPUT_ROOT}")

# เริ่มรันโปรแกรม
run_augmentation()

"""แบ่งไฟล์ข้อมูลออกเป็น 2 ชุด ( train set & valid set)"""

!pip install -q ultralytics
import os
import random
import shutil
from pathlib import Path
from google.colab import drive

# 1. เชื่อมต่อ Google Drive
drive.mount('/content/drive')

# 2. ตั้งค่าโฟลเดอร์ (แก้ไข Path ให้ตรงกับ Drive ของคุณ)
PROJECT_PATH = "/content/drive/MyDrive/phase4/3"
SOURCE_AUG_DIR = f"{PROJECT_PATH}/train_aug_obb"
FINAL_DATASET_DIR = f"{PROJECT_PATH}/final_dataset"

# ชื่อคลาส
CLASS_NAMES = {
  0: "Crack",
  1: "Efflorescence",
  2: "Porous_Defect",
  3: "Rust_Stained_Exposure",
  4: "Spalling",
  5: "Steel_Exposure",
  6: "strain"
}
TRAIN_RATIO = 0.8  # แบ่ง Train 80%, Val 20%

# 3. เริ่มกระบวนการแบ่งไฟล์
print("\n" + "="*50)
print("📦 [Phase 1] เริ่มกระบวนการแบ่งข้อมูล")
print("="*50)

src_img_dir = Path(SOURCE_AUG_DIR) / "images"
src_lbl_dir = Path(SOURCE_AUG_DIR) / "labels"

if not src_img_dir.exists():
    print(f"❌ หาโฟลเดอร์ไม่เจอ: {src_img_dir}")
else:
    all_images = [f for f in os.listdir(src_img_dir) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]
    print(f"🔍 พบรูปภาพทั้งหมด {len(all_images)} รูป")

    random.seed(42)
    random.shuffle(all_images)

    split_idx = int(len(all_images) * TRAIN_RATIO)
    train_imgs = all_images[:split_idx]
    val_imgs = all_images[split_idx:]

    for sub in ['train', 'val']:
        (Path(FINAL_DATASET_DIR) / sub / 'images').mkdir(parents=True, exist_ok=True)
        (Path(FINAL_DATASET_DIR) / sub / 'labels').mkdir(parents=True, exist_ok=True)

    def move_files(files, subset):
        for f in files:
            shutil.copy(src_img_dir / f, Path(FINAL_DATASET_DIR) / subset / 'images' / f)
            label_f = f.rsplit('.', 1)[0] + ".txt"
            if (src_lbl_dir / label_f).exists():
                shutil.copy(src_lbl_dir / label_f, Path(FINAL_DATASET_DIR) / subset / 'labels' / label_f)

    print("⏳ กำลังคัดลอกไฟล์ (ขั้นตอนนี้อาจใช้เวลานาน หากมีรูปเยอะ)...")
    move_files(train_imgs, 'train')
    move_files(val_imgs, 'val')
    print(f"✅ แบ่งไฟล์สำเร็จ! พร้อมเทรนแล้ว")

"""TRAIN model YOLO"""

# =========================================================
# ขั้นตอนที่ 0: ติดตั้ง Library และเชื่อมต่อ Drive
# =========================================================
!pip install -q ultralytics
import os
import yaml
from ultralytics import YOLO
from google.colab import drive

drive.mount('/content/drive')

# =========================================================
# ขั้นตอนที่ 1: ตั้งค่าโฟลเดอร์ (CONFIG)
# =========================================================
PROJECT_PATH = "/content/drive/MyDrive/phase4/3"

# ชี้ไปที่โฟลเดอร์ที่เคยแบ่ง Train/Val ไว้แล้ว
FINAL_DATASET_DIR = f"{PROJECT_PATH}/final_dataset"

# ชื่อคลาสทั้ง 6 คลาสของคุณ
CLASS_NAMES = {
  0: "Crack",
  1: "Efflorescence",
  2: "Porous_Defect",
  3: "Rust_Stained_Exposure",
  4: "Spalling",
  5: "Steel_Exposure",
  6: "strain"
}

# =========================================================
# ขั้นตอนที่ 2: ฟังก์ชันสร้าง YAML และเริ่มเทรนโมเดล (ข้ามการแบ่งไฟล์)
# =========================================================
def train_model():
    print("\n" + "="*50)
    print("🚀 เริ่มกระบวนการเทรน AI (YOLOv8-obb)")
    print("="*50)

    yaml_path = f"{FINAL_DATASET_DIR}/data.yaml"

    # โครงสร้างไฟล์ yaml
    data_yaml = {
        'train': f"{FINAL_DATASET_DIR}/train/images",
        'val': f"{FINAL_DATASET_DIR}/val/images",
        'nc': len(CLASS_NAMES),
        'names': [CLASS_NAMES[i] for i in range(len(CLASS_NAMES))]
    }

    # เขียนไฟล์ yaml ทับลงไป
    with open(yaml_path, 'w') as f:
        yaml.dump(data_yaml, f, default_flow_style=False)

    print(f"📝 สร้างไฟล์แผนที่ข้อมูลเสร็จสิ้น: {yaml_path}")
    print("🔥 กำลังโหลดโมเดลและเริ่มเทรน...")

    # โหลด YOLOv8 Nano และเริ่มเทรน
    model = YOLO("yolov8n-obb.pt")

    model.train(
        data=yaml_path,
        epochs=1000,     # จำนวนการทงาน (ตั้งเผื่อไว้เยอะๆ)
        patience=50,     # จุดยอมแพ้ มันคือ earlystop ของ model
        imgsz=640,
        batch=16,
        device=0,        # ใช้ GPU (T4)
        cache=True,
        project=f"{PROJECT_PATH}/runs",
        name="bridge_model"
    )
    print("\n🎉🎉🎉 เทรนเสร็จสมบูรณ์! น้ำหนักโมเดล (weights) อยู่ในโฟลเดอร์ runs 🎉🎉🎉")

train_model()

"""ถ้าสมมุติว่า ระหว่าง train คอมเกิดดับหรือมีปัญหาให้ใช้โค้ดตรงนี้เพื่อรันต่อจากเดิม ระวัง paramter ที่เปลี่ยนแปลงไปด้วย"""

from ultralytics import YOLO

# 1. ปลุกสมองตัวล่าสุดขึ้นมา (ย้ำว่าต้องเป็น last.pt)
resume_weights = "/content/drive/MyDrive/phase4/3/runs/bridge_model-2/weights/last.pt"
model = YOLO(resume_weights)

print("🚀 กำลังปลุก AI ให้ตื่นมาวิ่งผลัดต่อจากรอบที่แล้ว...")

model.train(resume=True)

"""หลัง train model เสร็จแล้ว เช็ค model เทียบกับ valid set"""

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/phase4/3/runs/bridge_model-2/weights/best.pt")

print("📊 กำลังสร้าง Confusion Matrix...")
# ทำการรัน Validation เพื่อวาดกราฟใหม่
metrics = model.val(data="/content/drive/MyDrive/phase4/3/final_dataset/data.yaml")
print("✅ เสร็จแล้ว! กราฟอยู่ในโฟลเดอร์ runs/detect/val ครับ")

"""เช็คข้อมูล และ evaluate model"""

import os
from IPython.display import Image, display

# =========================================================
# 1. ตั้งค่าโฟลเดอร์ (ชี้ไปที่โฟลเดอร์ val ที่เพิ่งสร้างกราฟเมื่อกี้)
RESULTS_DIR = "/content/runs/obb/val"

# =========================================================
# 2. รายชื่อไฟล์ที่ต้องการแสดงผล (เอาเฉพาะรูปที่ได้จาก .val())
files_to_show = [
    ("🔀 ตารางความสับสน (Confusion Matrix)", "confusion_matrix.png"),
    ("📈 กราฟความแม่นยำ F1 Curve", "BoxF1_curve.png"),
    ("📈 กราฟ PR Curve (โชว์ความโหดของ mAP)", "BoxPR_curve.png"),
    ("🖼️ ตัวอย่างการตรวจจับ - AI ทายผล (Predictions)", "val_batch0_pred.jpg")
]

# =========================================================
# 3. ฟังก์ชันดึงรูปมาแสดงผล
print("🔍 กำลังดึงผลลัพธ์การเทรนมาแสดง...")

for title, filename in files_to_show:
    filepath = os.path.join(RESULTS_DIR, filename)
    print("\n" + "="*60)
    print(title)
    print("="*60)
    if os.path.exists(filepath):
        display(Image(filename=filepath, width=1000))
    else:
        print(f"❌ ไม่พบไฟล์: {filename}")
        print(f"ลองเช็คดูว่าในโฟลเดอร์ {RESULTS_DIR} มีไฟล์นี้อยู่จริงหรือไม่")

print("\n✨ แสดงผลเสร็จสิ้น!")

"""นำโมเดล best มา เข้าตรวจสอบกับรูป test set (ตรงนี้ควรใช้รูปที่ไม่อยู่ใน valid และ train set)"""

# =========================================================
# ขั้นตอนที่ 1: ติดตั้งไลบรารีและเชื่อมต่อ Google Drive (สำหรับเปิด Colab ใหม่)
# =========================================================
!pip install -q ultralytics
from google.colab import drive
drive.mount('/content/drive')

import cv2
import matplotlib.pyplot as plt
from ultralytics import YOLO
from google.colab import files

print("\n" + "="*50)
print("🚀 เริ่มระบบ AI ตรวจจับความเสียหายของสะพาน")
print("="*50)

# =========================================================
# ขั้นตอนที่ 2: ตั้งค่า Path ไปหาไฟล์ best.pt ของคุณ

MODEL_PATH = "/content/drive/MyDrive/phase4/3/runs/bridge_model-2/weights/best.pt"

try:
    print("⏳ กำลังโหลดน้ำหนักโมเดลจาก Drive...")
    model = YOLO(MODEL_PATH)
    print("✅ โหลดสมอง AI สำเร็จ พร้อมใช้งาน!\n")
    model_loaded = True
except Exception as e:
    print(f"\n❌ โหลดโมเดลไม่สำเร็จ Error: {e}")
    print(f"💡 คำแนะนำ: ลองเช็คดูว่าไฟล์ {MODEL_PATH} มีอยู่จริงหรือไม่")
    model_loaded = False

# =========================================================
# ขั้นตอนที่ 3: อัปโหลดรูปและให้ AI ทายผล
# =========================================================
if model_loaded:
    print("📸 กดปุ่ม Choose Files ด้านล่าง เพื่ออัปโหลดรูปสะพานที่ต้องการทดสอบ")
    uploaded = files.upload()

    for filename in uploaded.keys():
        print(f"\n🔍 กำลังสแกนภาพ: {filename}...")

        # สั่งให้ AI ตรวจจับ (ปรับ conf=0.5 คือให้ AI มั่นใจเกิน 50% ถึงจะวาดกล่อง)
        results = model.predict(source=filename, conf=0.15, save=False)

        # ดึงภาพที่ถูกวาดเส้นแล้วออกมา
        res_plotted = results[0].plot()

        # แปลงสีให้แสดงผลใน Colab ได้ถูกต้อง (BGR -> RGB)
        res_rgb = cv2.cvtColor(res_plotted, cv2.COLOR_BGR2RGB)

        # ตั้งค่าแสดงผลให้ใหญ่และชัดเจน
        plt.figure(figsize=(12, 12))
        plt.imshow(res_rgb)
        plt.axis('off') # ปิดกรอบตัวเลขแกน X, Y
        plt.title(f"ผลการประเมิน: {filename}", fontsize=16)
        plt.show()

    print("\n✨ ตรวจจับเสร็จสิ้น!")